# Generated by Django 3.2.7 on 2021-10-29 05:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnVerifiedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=40)),
                ('Second_Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('Photo', models.TextField(null=True)),
                ('password', models.CharField(max_length=128)),
                ('OTP', models.CharField(max_length=6)),
                ('Generated_Date', models.DateTimeField(auto_now_add=True)),
                ('Phone', models.CharField(max_length=13)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('First_Name', models.CharField(max_length=40)),
                ('Second_Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('Photo', models.TextField(blank=True, null=True)),
                ('Phone', models.CharField(max_length=13)),
                ('Gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManagement.gender')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
