# Generated by Django 3.2.7 on 2021-09-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('First_Name', models.CharField(max_length=40)),
                ('Second_Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('Photo', models.TextField()),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.gender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnVerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Second_Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False)),
                ('Photo', models.TextField()),
                ('password', models.CharField(max_length=300)),
                ('OTP', models.CharField(max_length=6)),
                ('Generated_Date', models.DateField(auto_now_add=True)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.gender')),
            ],
        ),
    ]
