# Generated by Django 3.2.7 on 2021-09-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_alter_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.gender'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
