# Generated by Django 3.2.7 on 2021-10-09 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifieduser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
