# Generated by Django 3.2.7 on 2021-10-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0007_alter_unverifieduser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManagement.gender'),
        ),
    ]
