# Generated by Django 3.2.7 on 2021-10-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0008_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifieduser',
            name='Generated_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
