# Generated by Django 3.2.7 on 2021-10-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_alter_unverifieduser_generated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='Phone',
            field=models.CharField(default='-', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='Phone',
            field=models.CharField(default='-', max_length=13),
            preserve_default=False,
        ),
    ]
