# Generated by Django 3.2.7 on 2021-10-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Completed_Return_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pick_up_date', models.DateField()),
                ('Tracking_ID', models.CharField(max_length=20)),
                ('Recived_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompletedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('Delivery_Date', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Tracking_ID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Price', models.CharField(max_length=10)),
                ('Product_details', models.JSONField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('O', 'ORDERED'), ('D', 'DISPATCHED'), ('S', 'SHIPED'), ('OD', 'OUT FOR DELIVERY'), ('D', 'DONE')], max_length=2)),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('Quantity', models.IntegerField()),
                ('Tracking_ID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Return_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pick_up_date', models.DateField()),
                ('Status', models.CharField(choices=[('P', 'PICKED'), ('S', 'SHIPED'), ('R', 'RECIVED')], max_length=2)),
                ('Tracking_ID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.items')),
            ],
        ),
    ]
