# Generated by Django 3.2.7 on 2021-09-25 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_items',
            name='Recived_Date',
        ),
        migrations.AddField(
            model_name='return_items',
            name='Status',
            field=models.CharField(choices=[('P', 'PICKED'), ('S', 'SHIPED'), ('R', 'RECIVED')], default='-', max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Completed_Return_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pick_up_date', models.DateField()),
                ('Tracking_ID', models.CharField(max_length=20)),
                ('Recived_Date', models.DateField()),
                ('Return_Items_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.return_items')),
            ],
        ),
    ]
