# Generated by Django 3.2.7 on 2021-09-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210925_1033'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='belongs',
            table='sub Categorie',
        ),
    ]
