# Generated by Django 3.2.7 on 2021-10-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Display_Image',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
