# Generated by Django 3.2.7 on 2021-10-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_belongs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='belongs',
            table=None,
        ),
    ]
