# Generated by Django 3.2.7 on 2021-10-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_items_display_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='belongs',
            table='Sub_Categories',
        ),
    ]
