# Generated by Django 3.2.7 on 2021-10-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_belongs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='belongs',
            table=None,
        ),
    ]
